### ISSUE TITLE
As an admin, I want a button on the Admin Tools page that opens a file explorer dialogue that will allow me to select a CSV file as permanent storage

### ISSUE THREAD

**Issue by Kohmei358** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#100]

**Comment by gearymich** [comment]
Function should likely return File object found instead of void. Still need to upload data from CSV onto application to be used. How will this be visually mapped?

**Comment by gearymich** [comment]
I also failed to make a feature branch for this, all additions for this story were pushed directly onto UI-Staging. Apologies :(. (Branch was up to date however).

**Comment by Kohmei358** [comment]
I put the button in the right place (if that's what you mean by visually mapped)
No problem pushing to staging, we don't have too many people working on changes yet
