### ISSUE TITLE
Given a starting and ending location, your application will demonstrate a path drawn on the campus floor plan for which you created CSV files in Project B.

### ISSUE THREAD

**Issue by beast-nev** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#138]
![](https://i.ibb.co/4MYbbDz/Screen-Shot-2021-02-22-at-6-53-54-AM.png,"")

**Comment by cvkittler** [comment]
aStar() in graph manager returns a LinkedList of nodes
Node.getCords() returns an array of type Double [xCoord, yCoord]
