### ISSUE TITLE
(Port Over) - Map tool that allows a hospital administrator to create an undirected graph.

### ISSUE THREAD

**Issue by beast-nev** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#139]
It should be possible to add, modify and remove nodes; and add, modify and remove edges. The application should be able to load a CSV text file with nodes and edges. 
The nodes and edges should be able to be saved into a CSV text file.

**Comment by Kohmei358** [comment]
This is all in the folder (oldCSV's and oldFXML) it just needs to be brought over and beautified.

**Comment by Kohmei358** [comment]
Should look something like this:
![Nothing](https://i.ibb.co/sFBhV12/Screen-Shot-2021-02-22-at-6-48-13-AM.png "Nothing")

**Comment by Kohmei358** [comment]
I don't think GraphManger is setup to doAdjacentNodes so that's optional
