### ISSUE TITLE
You're accessing paths wrong

### ISSUE THREAD

**Issue by ArchdukeTim** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#143]
https://github.com/CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp/blob/fe289d194fb1373d4dfa0935c3538af29380cd43/src/main/java/edu/wpi/u/models/DatabaseManager.java#L89

Please Read https://github.com/WPISoftEng/SoftEngGuide/blob/master/javafx/resources.md and share with other teams

**Comment by Kohmei358** [comment]
Accidentally fixed as part of #148
