### ISSUE TITLE
make the depth-first search

### ISSUE THREAD

**Issue by cvkittler** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#4]
**Write a depth-first search algorithm** and test it on a very simple map with nodes and edges that you create yourselves.

Submit:
The A* algorithm IntelliJ project along with your simple map. You do not need to submit the depth-first search pathfinding program.

- [ ] Write the Depth First Search algorithm 
- [ ] Test DFS on the Simple Map

**Comment by Kohmei358** [comment]
Duplicate of #9

**Comment by Kohmei358** [comment]
Sorry didn't mean to close this
