### ISSUE TITLE
Setup CRUD for MapUNodes & MapUEdges

### ISSUE THREAD

**Issue by beast-nev** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#81]
Create, Read, Update, Delete

- [ ] Need functionality for creating new nodes / edges (insert into TABLE)
- [ ] Need functionality for reading all nodes / edges (select * TABLE)
- [ ] Need functionality for updating any nodes / edges (update x where y from TABLE)
- [ ] Need functionality for deleting any nodes / edges (delete x where y from TABLE)

**Comment by Kohmei358** [comment]
Did we talk about making this an epic and making each operation a story?
