### ISSUE TITLE
simple Node-Edge Map for DFS Testing

### ISSUE THREAD

**Issue by gearymich** [CS3733-C21-Team-U/CS3733-C21-Team-U-Project-BWApp#9]
Write a depth-first search algorithm and test it on a very simple map with **nodes and edges that you create yourselves.**

Submit:
The A* algorithm IntelliJ project along with your simple map. You do not need to submit the depth-first search pathfinding program.

**Comment by Kohmei358** [comment]
From OH:

- Edge are bi-directional
- Add intermediate nodes so that every edge is straight
